[package]
name = "nel"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
reqwest = "0.12.11"
tokio = { version = "1.42.0", features = ["full"] }
serde_json = "1.0.134"
dotenv = "0.15.0"
atomic_float = "1.1.0"
